Hazelcast-Management-Center:
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/hazlecast
  labels:
   io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  restart: always
  ports:
   - 8888:8080
  command: bash /usr/local/tomcat/bin/start-tomcat.sh start  
Hazelcast:
  image: 035824440926.dkr.ecr.us-east-1.amazonaws.com/nrt/hazlecast-service
  labels:
   io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  restart: always
  command: bash /usr/local/aeris_lib/start-hazelcast.sh "$${stack_name}"_"$${service_name}" ${hz_scale} "Hazelcast-Management-Center"
  links: 
   - Hazelcast-Management-Center:Hazelcast-Management-Center
  environment:
  - JVMFLAGS=-Xmx${hz_heap_size}g
  - INITOCFRACTION=${hz_init_frac}
  - MAXHEAPFREERATIO=${hz_max_heap_free}
  - MINHEAPFREERATIO=${hz_min_heap_free}
